name: Ubuntu Cinnamon Remix 20.04.2 Focal Daily

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: ' 0 14 * * * '

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: debian:latest
      options: --privileged -it

    steps:
    - uses: actions/checkout@v2

    - name: Install debootstrap/git
      run: apt update && apt install git debootstrap -y

    - name: Copy debootstrap scripts to distro
      run: |
        cd /usr/share/debootstrap/scripts
        cp disco focal


    - name: Build ISO
      run: |
        cd /
        git clone https://github.com/Ubuntu-Cinnamon-Remix/iso-builder -b focal
        cd iso-builder
        ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: Ubuntu Cinnamon Remix 20.04.2 Focal Daily
        path: /iso-builder/builds/
